#!/usr/bin/env python3
"""
Gemini Agent for Code Analysis, Audit, and Mathematical Feedback
Reads the prtoe_class repository and provides:
- Code summary
- Code audit
- Mathematical feedback
"""

import os
import json
from pathlib import Path
import google.generativeai as genai

# Configure Gemini API
API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    raise ValueError("GEMINI_API_KEY environment variable not set")

genai.configure(api_key=API_KEY)


def read_repository_files(repo_path=".", extensions=None):
    """
    Read all relevant files from the repository.
    
    Args:
        repo_path: Path to the repository root
        extensions: List of file extensions to include (default: .py, .md, .ini)
    
    Returns:
        Dictionary with file paths and contents
    """
    if extensions is None:
        extensions = [".py", ".md", ".ini", ".yaml"]
    
    files_content = {}
    repo = Path(repo_path)
    
    # Skip these directories
    skip_dirs = {".git", ".github", "output", "chains", "__pycache__", ".pytest_cache"}
    
    for file_path in repo.rglob("*"):
        # Skip directories and hidden files
        if file_path.is_dir():
            continue
        if any(part in skip_dirs for part in file_path.parts):
            continue
        if file_path.name.startswith("."):
            continue
        
        # Check file extension
        if file_path.suffix not in extensions:
            continue
        
        # Read file content
        try:
            relative_path = file_path.relative_to(repo)
            with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
                files_content[str(relative_path)] = content
        except Exception as e:
            print(f"Warning: Could not read {file_path}: {e}")
    
    return files_content


def create_analysis_prompt(files_content):
    """
    Create a comprehensive prompt for Gemini to analyze the code.
    
    Args:
        files_content: Dictionary with file paths and contents
    
    Returns:
        Formatted prompt string
    """
    file_list = "\n".join([f"- {path} ({len(content)} chars)" for path, content in files_content.items()])
    
    prompt = f"""You are an expert code reviewer and mathematician. Analyze the provided repository code and provide comprehensive feedback.

Repository Files:
{file_list}

---

Here are all the repository files:

"""
    
    for file_path, content in sorted(files_content.items()):
        prompt += f"\n\n### FILE: {file_path}\n```\n{content}\n```\n"
    
    prompt += """

---

Please provide a detailed analysis with the following sections:

## 1. CODE SUMMARY
Provide a comprehensive overview of:
- What this project does
- Main modules and their purposes
- Key classes and functions
- Overall architecture

## 2. CODE AUDIT
Evaluate the code for:
- Code quality and style
- Potential bugs or issues
- Performance concerns
- Security vulnerabilities (if any)
- Best practices compliance
- Error handling adequacy

## 3. MATHEMATICAL FEEDBACK
Analyze the mathematical aspects:
- Correctness of mathematical implementations
- Numerical stability
- Algorithm efficiency
- Accuracy of calculations
- Any mathematical inconsistencies or errors
- Suggestions for mathematical improvements

## 4. RECOMMENDATIONS
Provide actionable recommendations for:
- Code improvements
- Performance optimizations
- Mathematical enhancements
- Testing suggestions
- Documentation improvements

Please be thorough and specific in your feedback, referencing file names and line numbers where applicable."""
    
    return prompt


def analyze_code(files_content):
    """
    Use Gemini to analyze the code.
    
    Args:
        files_content: Dictionary with file paths and contents
    
    Returns:
        Analysis response from Gemini
    """
    prompt = create_analysis_prompt(files_content)
    
    # Use Gemini API to analyze
    model = genai.GenerativeModel("gemini-2.0-flash")
    response = model.generate_content(prompt)
    
    return response.text


def save_analysis(analysis, output_file="GEMINI_ANALYSIS.md"):
    """
    Save the analysis to a file.
    
    Args:
        analysis: Analysis text from Gemini
        output_file: Output file name
    """
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# prtoe_class Repository Analysis\n\n")
        f.write("Generated by Gemini Agent\n\n")
        f.write(analysis)
    
    print(f"Analysis saved to {output_file}")


def main():
    """Main execution function."""
    print("Starting Gemini Code Analysis Agent...")
    print("=" * 60)
    
    # Read repository files
    print("\n1. Reading repository files...")
    files_content = read_repository_files()
    print(f"   Found {len(files_content)} files to analyze")
    for file_path in sorted(files_content.keys()):
        print(f"   - {file_path}")
    
    # Analyze with Gemini
    print("\n2. Analyzing code with Gemini...")
    print("   (This may take a moment...)")
    analysis = analyze_code(files_content)
    
    # Save analysis
    print("\n3. Saving analysis...")
    save_analysis(analysis)
    
    # Print summary
    print("\n" + "=" * 60)
    print("Analysis Complete!")
    print("=" * 60)
    print("\nFirst 500 characters of analysis:\n")
    print(analysis[:500] + "...\n")
    print("Full analysis saved to GEMINI_ANALYSIS.md")


if __name__ == "__main__":
    main()
