debug: true
output: chains/prtoe_poly
likelihood:
  planck_2018_lowl.TT: null
  planck_2018_lowl.EE: null
  planck_2018_highl_plik.TTTEEE_lite: null
  planck_2018_lensing.clik: null
  bao.sixdf_2011_bao: null
  bao.sdss_dr7_mgs: null
  bao.sdss_dr12_consensus_final: null
  bao.desi_2024_bao_all: null
  sn.pantheonplusshoes: null
theory:
  classy:
    path: /home/themilkmanj/prtoe_class
    stop_at_error: false
    extra_args:
      use_prtoe: 'yes'
      non_linear: halofit
      output: mPk,tCl,pCl,lCl
      modes: s
      N_ur: 2.0328
      N_ncdm: 1
      T_ncdm: 0.71611
      base_path: /home/themilkmanj/prtoe_class
params:
  omega_b:
    prior:
      min: 0.019
      max: 0.026
    ref: 0.0224
    proposal: 0.0001
    latex: \Omega_\mathrm{b} h^2
  omega_cdm:
    prior:
      min: 0.1
      max: 0.2
    ref: 0.12
    proposal: 0.001
    latex: \Omega_\mathrm{c} h^2
  H0:
    prior:
      min: 55.0
      max: 85.0
    ref: 67.4
    proposal: 0.5
    latex: H_0
  logA:
    prior:
      min: 1.61
      max: 3.91
    ref: 3.05
    proposal: 0.001
    latex: \ln(10^{10} A_\mathrm{s})
    drop: true
  A_s:
    value: 'lambda logA: 1e-10 * np.exp(logA)'
  n_s:
    prior:
      min: 0.8
      max: 1.2
    ref: 0.965
    proposal: 0.005
    latex: n_\mathrm{s}
  z_reio:
    prior:
      min: 5.0
      max: 12.0
    ref: 8.0
    proposal: 0.1
    latex: z_\mathrm{reio}
  A_planck:
    prior:
      dist: norm
      loc: 1.0
      scale: 0.0025
    ref: 1.0
    proposal: 0.00025
    latex: A_\mathrm{planck}
  xi_prtoe:
    prior:
      min: 1.0e-07
      max: 1.2e-05
    ref: 1.0e-07
    proposal: 1.0e-08
    latex: \xi_\mathrm{prtoe}
  zeta_prtoe:
    prior:
      min: 0.0001
      max: 5.0
    ref: 0.1
    proposal: 0.05
    latex: \zeta_\mathrm{prtoe}
  V0_prtoe:
    value: 'lambda omega_b, omega_cdm, H0: 1.0 - (omega_b + omega_cdm) / (H0/100.0)**2'
    latex: V_{0,\mathrm{prtoe}}
  lambda_prtoe:
    value: 0.05
    latex: \lambda_\mathrm{prtoe}
  m_prtoe:
    value: 0.05
    latex: m_\mathrm{prtoe}
  phi_0_prtoe:
    value: 1.0
    latex: \phi_{0,\mathrm{prtoe}}
  m_ncdm:
    value: 0.06
    latex: \sum m_\nu \ [\mathrm{eV}]
  beta_prtoe:
    value: 1.0e-6
    latex: \beta_\mathrm{prtoe}
  M_prtoe:
    value: 100.0
    latex: M_\mathrm{prtoe}
  alpha_prtoe:
    value: 0.1
    latex: \alpha_\mathrm{prtoe}
  M_ew_prtoe:
    value: 100.0
    latex: M_{\mathrm{ew},\mathrm{prtoe}}
  H_vac_floor:
    value: 64.1218
    latex: H_{\mathrm{vac,floor}}
  delta_prtoe:
    value: 0.0
    latex: \Delta_\mathrm{prtoe}
sampler:
  polychord:
    nlive: 200
    num_repeats: 80
    precision_criterion: 0.001
